version: 2.1
orbs: 
  apex: circleci/salesforce-apex@1.0.1
jobs: 
  install_authenticate_deploy: 
    docker: 
      - image: cimg/node:14.5
    steps: 
      - checkout
      - apex/setup: 
          defaultusername: admin@blooddonor.com
      - run: 
          name: Convert from source to metadata format
          command: sfdx force:source:convert -d tmp_convert
      - run:
          name: Deploy to Salesforce Org
          command: sfdx force:mdapi:deploy --deploydir tmp_convert --testlevel RunLocalTests --verbose
workflows: 
  basic-test: 
    jobs: 
      - install_authenticate_deploy